import { addDays } from "./format";
import {
  HORIZON_END,
  WEEK_START,
  type Asset,
  type Resource,
  type Station,
  type SectionRow,
  type Task,
  type TrainPath,
  type WindowSlot,
} from "./types";

export const STATIONS: Station[] = [
  { code: "NDLS", name: "New Delhi", km: 0 },
  { code: "SZM", name: "Subzi Mandi", km: 4 },
  { code: "ANDI", name: "Adarsh Nagar", km: 11 },
  { code: "NUR", name: "Narela", km: 27 },
  { code: "SNP", name: "Sonipat", km: 44 },
  { code: "GNU", name: "Ganaur", km: 55 },
  { code: "SMK", name: "Samalkha", km: 64 },
  { code: "PNP", name: "Panipat Jn", km: 89 },
  { code: "GRA", name: "Gharaunda", km: 111 },
  { code: "KUN", name: "Karnal", km: 123 },
  { code: "NLKR", name: "Nilokheri", km: 141 },
  { code: "KKDE", name: "Kurukshetra Jn", km: 156 },
  { code: "SHDM", name: "Shahbad Markanda", km: 174 },
  { code: "UMB", name: "Ambala Cantt", km: 199 },
];

export const SECTIONS: SectionRow[] = [
  { id: "s1", label: "NDLS–SNP", fromKm: 0, toKm: 44 },
  { id: "s2", label: "SNP–PNP", fromKm: 44, toKm: 89 },
  { id: "s3", label: "PNP–KUN", fromKm: 89, toKm: 123 },
  { id: "s4", label: "KUN–KKDE", fromKm: 123, toKm: 156 },
  { id: "s5", label: "KKDE–UMB", fromKm: 156, toKm: 199 },
];

export const RESOURCES: Resource[] = [
  { id: "r-pwm-snp", name: "P.Way gang SNP", kind: "GANG", department: "ENGG", base: "SNP", capacity: 1 },
  { id: "r-pwm-pnp", name: "P.Way gang PNP", kind: "GANG", department: "ENGG", base: "PNP", capacity: 1 },
  { id: "r-pwm-kkde", name: "P.Way gang KKDE", kind: "GANG", department: "ENGG", base: "KKDE", capacity: 1 },
  { id: "r-bcm", name: "BCM-14 ballast cleaner", kind: "MACHINE", department: "ENGG", base: "UMB", capacity: 1 },
  { id: "r-unimat", name: "UNIMAT tamping PNP", kind: "MACHINE", department: "ENGG", base: "PNP", capacity: 1 },
  { id: "r-usfd", name: "USFD party NDLS", kind: "CREW", department: "ENGG", base: "NDLS", capacity: 1 },
  { id: "r-snt-pnp", name: "S&T gang PNP", kind: "GANG", department: "SNT", base: "PNP", capacity: 1 },
  { id: "r-snt-umb", name: "S&T gang UMB", kind: "GANG", department: "SNT", base: "UMB", capacity: 1 },
  { id: "r-ei", name: "EI specialist cell", kind: "CREW", department: "SNT", base: "NDLS", capacity: 1 },
  { id: "r-tw14", name: "Tower wagon TW-14", kind: "MACHINE", department: "TRD", base: "PNP", capacity: 1 },
  { id: "r-tw07", name: "Tower wagon TW-07", kind: "MACHINE", department: "TRD", base: "UMB", capacity: 1 },
  { id: "r-psi", name: "PSI / AT crew", kind: "CREW", department: "TRD", base: "PNP", capacity: 1 },
];

const E = WEEK_START;
const L = HORIZON_END;

export const TASKS: Task[] = [
  {
    id: "T-ENGG-001",
    source: "TMS",
    department: "ENGG",
    title: "Deep screening km 42.0–47.5 Up",
    detail: "Ballast fouling 48% SNP–GNU. BCM possession with through packing. TSR 30 currently in force.",
    fromKm: 42,
    toKm: 47.5,
    line: "UP",
    durationHours: 5.5,
    severity: 5,
    overdueDays: 21,
    trafficImpact: 88,
    safetyRisk: 86,
    resourceIds: ["r-bcm", "r-pwm-snp"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-ENGG-002",
    source: "TMS",
    department: "ENGG",
    title: "1 in 12 turnout renewal PNP yard L3",
    detail: "Worn crossing and chipped switch. UNIMAT + P.Way. Affects goods reception.",
    fromKm: 88.4,
    toKm: 90.2,
    line: "BOTH",
    durationHours: 6,
    severity: 4,
    overdueDays: 14,
    trafficImpact: 92,
    safetyRisk: 74,
    resourceIds: ["r-unimat", "r-pwm-pnp"],
    earliest: E,
    latest: addDays(E, 14),
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-ENGG-003",
    source: "TMS",
    department: "ENGG",
    title: "USFD testing km 118–138 Dn",
    detail: "Quarterly ultrasonic of 60kg 90UTS. Two rail-end defects pending confirmation.",
    fromKm: 118,
    toKm: 138,
    line: "DN",
    durationHours: 3,
    severity: 3,
    overdueDays: 9,
    trafficImpact: 40,
    safetyRisk: 62,
    resourceIds: ["r-usfd"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-ENGG-004",
    source: "TMS",
    department: "ENGG",
    title: "Through packing km 154.0–159.5 Up",
    detail: "Voiding under sleeper after monsoon. UNIMAT run with lifting.",
    fromKm: 154,
    toKm: 159.5,
    line: "UP",
    durationHours: 4,
    severity: 3,
    overdueDays: 6,
    trafficImpact: 55,
    safetyRisk: 48,
    resourceIds: ["r-unimat", "r-pwm-kkde"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-ENGG-005",
    source: "BDMS",
    department: "ENGG",
    title: "Bridge 214 bearing inspection",
    detail: "Steel girder over canal near GRA. Night possession, no machine.",
    fromKm: 108.2,
    toKm: 108.8,
    line: "BOTH",
    durationHours: 3.5,
    severity: 4,
    overdueDays: 18,
    trafficImpact: 60,
    safetyRisk: 80,
    resourceIds: ["r-pwm-pnp"],
    earliest: E,
    latest: addDays(E, 10),
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-ENGG-006",
    source: "TMS",
    department: "ENGG",
    title: "AT welding backlog km 22–31 Up",
    detail: "14 junctions due. Destressing window required.",
    fromKm: 22,
    toKm: 31,
    line: "UP",
    durationHours: 4.5,
    severity: 3,
    overdueDays: 27,
    trafficImpact: 50,
    safetyRisk: 58,
    resourceIds: ["r-pwm-snp"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-ENGG-007",
    source: "TMS",
    department: "ENGG",
    title: "LC-29 cess repair & check rail",
    detail: "Manned LC at km 63.4 SMK. Road crust failed. Needs S&T boom test after.",
    fromKm: 63,
    toKm: 64,
    line: "BOTH",
    durationHours: 3,
    severity: 4,
    overdueDays: 11,
    trafficImpact: 70,
    safetyRisk: 84,
    resourceIds: ["r-pwm-snp"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-ENGG-008",
    source: "TMS",
    department: "ENGG",
    title: "Rail renewal 60kg km 171–176 Dn",
    detail: "GMT expired panel. 1.2 km insertion. Needs TRD bonding restoration.",
    fromKm: 171,
    toKm: 176,
    line: "DN",
    durationHours: 6,
    severity: 4,
    overdueDays: 8,
    trafficImpact: 78,
    safetyRisk: 70,
    resourceIds: ["r-pwm-kkde", "r-bcm"],
    earliest: addDays(E, 3),
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-ENGG-009",
    source: "TMS",
    department: "ENGG",
    title: "Formation repair km 12.5–14.0 Dn",
    detail: "Slacks after monsoon near ANDI. Manual packing, 20 kmph TSR.",
    fromKm: 12.5,
    toKm: 14,
    line: "DN",
    durationHours: 3,
    severity: 3,
    overdueDays: 4,
    trafficImpact: 45,
    safetyRisk: 52,
    resourceIds: ["r-pwm-snp"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-ENGG-010",
    source: "TMS",
    department: "ENGG",
    title: "Catch siding inspection UMB",
    detail: "Annual inspection of catch siding and sand drag. Yard block.",
    fromKm: 197,
    toKm: 199,
    line: "BOTH",
    durationHours: 2.5,
    severity: 2,
    overdueDays: 2,
    trafficImpact: 35,
    safetyRisk: 40,
    resourceIds: ["r-pwm-kkde"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-ENGG-011",
    source: "TMS",
    department: "ENGG",
    title: "Seized ERCs km 95–102 Up",
    detail: "Corroded clips on curve. Gang + material already staged at PNP.",
    fromKm: 95,
    toKm: 102,
    line: "UP",
    durationHours: 3,
    severity: 2,
    overdueDays: 16,
    trafficImpact: 30,
    safetyRisk: 36,
    resourceIds: ["r-pwm-pnp"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-ENGG-012",
    source: "BDMS",
    department: "ENGG",
    title: "Trolley inspection km 0–20 Up",
    detail: "AEN trolley. Can run in shadow of other Up possessions.",
    fromKm: 0,
    toKm: 20,
    line: "UP",
    durationHours: 2,
    severity: 1,
    overdueDays: 0,
    trafficImpact: 15,
    safetyRisk: 20,
    resourceIds: ["r-pwm-snp"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-SNT-001",
    source: "SMMS",
    department: "SNT",
    title: "Point machine replacement PNP-12A",
    detail: "IRS point machine hunting. Yard line 3 — pair with turnout renewal.",
    fromKm: 88.6,
    toKm: 90.0,
    line: "BOTH",
    durationHours: 4,
    severity: 4,
    overdueDays: 12,
    trafficImpact: 90,
    safetyRisk: 78,
    resourceIds: ["r-snt-pnp"],
    earliest: E,
    latest: addDays(E, 14),
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-SNT-002",
    source: "SMMS",
    department: "SNT",
    title: "Axle counter reset & rail contacts KKDE",
    detail: "MSDAC intermittent occupancies on Up home. Joint with P.Way packing.",
    fromKm: 154.5,
    toKm: 157.5,
    line: "UP",
    durationHours: 3,
    severity: 4,
    overdueDays: 7,
    trafficImpact: 72,
    safetyRisk: 82,
    resourceIds: ["r-snt-umb"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-SNT-003",
    source: "SMMS",
    department: "SNT",
    title: "EI module swap SNP cabin",
    detail: "Westinghouse EI I/O card failing. Requires yard block + TRD AT isolation.",
    fromKm: 43,
    toKm: 45.5,
    line: "BOTH",
    durationHours: 4.5,
    severity: 5,
    overdueDays: 3,
    trafficImpact: 95,
    safetyRisk: 88,
    resourceIds: ["r-ei", "r-snt-pnp"],
    earliest: E,
    latest: addDays(E, 7),
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-SNT-004",
    source: "SMMS",
    department: "SNT",
    title: "LC-29 interlocking & boom test",
    detail: "Must follow cess repair. Barrier mechanism and road signals.",
    fromKm: 63,
    toKm: 64,
    line: "BOTH",
    durationHours: 2.5,
    severity: 4,
    overdueDays: 11,
    trafficImpact: 68,
    safetyRisk: 86,
    resourceIds: ["r-snt-pnp"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-SNT-005",
    source: "SMMS",
    department: "SNT",
    title: "Signal cable meggering km 170–178",
    detail: "Insulation drop after rains. Quad cable to SHDM.",
    fromKm: 170,
    toKm: 178,
    line: "DN",
    durationHours: 3.5,
    severity: 3,
    overdueDays: 5,
    trafficImpact: 42,
    safetyRisk: 55,
    resourceIds: ["r-snt-umb"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-SNT-006",
    source: "BDMS",
    department: "SNT",
    title: "LED main signal replacement GRA Dn",
    detail: "Distant signal lamp voltage low. Ladder working with power block preferred.",
    fromKm: 109.5,
    toKm: 111.5,
    line: "DN",
    durationHours: 2.5,
    severity: 3,
    overdueDays: 19,
    trafficImpact: 48,
    safetyRisk: 60,
    resourceIds: ["r-snt-pnp"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-SNT-007",
    source: "SMMS",
    department: "SNT",
    title: "Track circuit bonding km 22–31 Up",
    detail: "Bonds to be restored after AT welding. Same possession as welding party.",
    fromKm: 22,
    toKm: 31,
    line: "UP",
    durationHours: 2,
    severity: 3,
    overdueDays: 27,
    trafficImpact: 44,
    safetyRisk: 50,
    resourceIds: ["r-snt-pnp"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-SNT-008",
    source: "SMMS",
    department: "SNT",
    title: "IBS hut battery bank NUR–SNP",
    detail: "VRLA end-of-life. Can be shadow-blocked if Up is already under possession.",
    fromKm: 34,
    toKm: 38,
    line: "UP",
    durationHours: 2.5,
    severity: 2,
    overdueDays: 8,
    trafficImpact: 28,
    safetyRisk: 34,
    resourceIds: ["r-snt-pnp"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-SNT-009",
    source: "SMMS",
    department: "SNT",
    title: "Point detection adjustment KUN-3B",
    detail: "Out-of-correspondence alarms. 90 min plus testing.",
    fromKm: 122.4,
    toKm: 124,
    line: "BOTH",
    durationHours: 2,
    severity: 3,
    overdueDays: 1,
    trafficImpact: 58,
    safetyRisk: 64,
    resourceIds: ["r-snt-pnp"],
    earliest: E,
    latest: addDays(E, 10),
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-SNT-010",
    source: "SMMS",
    department: "SNT",
    title: "TPWS balise calibration km 0–8",
    detail: "After NDLS remodelling residual. Night only.",
    fromKm: 0,
    toKm: 8,
    line: "UP",
    durationHours: 3,
    severity: 2,
    overdueDays: 30,
    trafficImpact: 40,
    safetyRisk: 30,
    resourceIds: ["r-ei"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-TRD-001",
    source: "TDMS",
    department: "TRD",
    title: "Contact wire renewal km 88.2–92.4",
    detail: "Wear at 25%. Tower wagon TW-14. Pair with PNP yard Engg/S&T.",
    fromKm: 88.2,
    toKm: 92.4,
    line: "UP",
    durationHours: 5,
    severity: 4,
    overdueDays: 13,
    trafficImpact: 85,
    safetyRisk: 72,
    resourceIds: ["r-tw14"],
    earliest: E,
    latest: addDays(E, 14),
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-TRD-002",
    source: "TDMS",
    department: "TRD",
    title: "Cantilever replacement km 42.8–46.0 Up",
    detail: "Bent cantilever after tree fall. Same stretch as deep screening.",
    fromKm: 42.8,
    toKm: 46,
    line: "UP",
    durationHours: 4,
    severity: 4,
    overdueDays: 20,
    trafficImpact: 80,
    safetyRisk: 76,
    resourceIds: ["r-tw14"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-TRD-003",
    source: "TDMS",
    department: "TRD",
    title: "ATD maintenance SNP–GNU",
    detail: "Auto tensioning device winter setting overdue.",
    fromKm: 44,
    toKm: 55,
    line: "DN",
    durationHours: 3,
    severity: 3,
    overdueDays: 15,
    trafficImpact: 50,
    safetyRisk: 48,
    resourceIds: ["r-tw14"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-TRD-004",
    source: "TDMS",
    department: "TRD",
    title: "Insulator washing km 154–162",
    detail: "Pollution flashover risk near KKDE. Needs power block.",
    fromKm: 154,
    toKm: 162,
    line: "UP",
    durationHours: 3,
    severity: 3,
    overdueDays: 6,
    trafficImpact: 58,
    safetyRisk: 54,
    resourceIds: ["r-tw07"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-TRD-005",
    source: "TDMS",
    department: "TRD",
    title: "Bonding restoration km 171–176 Dn",
    detail: "After rail renewal. Traction bonds and impedance bonds.",
    fromKm: 171,
    toKm: 176,
    line: "DN",
    durationHours: 2.5,
    severity: 4,
    overdueDays: 0,
    trafficImpact: 65,
    safetyRisk: 60,
    resourceIds: ["r-tw07", "r-psi"],
    earliest: addDays(E, 3),
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-TRD-006",
    source: "TDMS",
    department: "TRD",
    title: "SSP Panipat isolator overhaul",
    detail: "Motorised isolator sluggish. Power block PNP–GRA.",
    fromKm: 86,
    toKm: 94,
    line: "BOTH",
    durationHours: 4,
    severity: 3,
    overdueDays: 10,
    trafficImpact: 74,
    safetyRisk: 58,
    resourceIds: ["r-psi"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-TRD-007",
    source: "BDMS",
    department: "TRD",
    title: "Dropper replacement km 12–16 Dn",
    detail: "Broken droppers reported by Loco Inspector. Short power block.",
    fromKm: 12,
    toKm: 16,
    line: "DN",
    durationHours: 2.5,
    severity: 3,
    overdueDays: 4,
    trafficImpact: 42,
    safetyRisk: 50,
    resourceIds: ["r-tw14"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-TRD-008",
    source: "TDMS",
    department: "TRD",
    title: "AT supply transformer oil test PNP",
    detail: "Annual BDV test. Can share SSP possession.",
    fromKm: 88,
    toKm: 90,
    line: "BOTH",
    durationHours: 2,
    severity: 2,
    overdueDays: 22,
    trafficImpact: 20,
    safetyRisk: 28,
    resourceIds: ["r-psi"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-TRD-009",
    source: "TDMS",
    department: "TRD",
    title: "OHE height/stagger km 198–199",
    detail: "UMB yard portals. After catch-siding inspection.",
    fromKm: 198,
    toKm: 199,
    line: "BOTH",
    durationHours: 2,
    severity: 2,
    overdueDays: 2,
    trafficImpact: 32,
    safetyRisk: 30,
    resourceIds: ["r-tw07"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-TRD-010",
    source: "TDMS",
    department: "TRD",
    title: "Section insulator replacement NUR",
    detail: "Worn SI on Up. Tower wagon from PNP.",
    fromKm: 26,
    toKm: 28,
    line: "UP",
    durationHours: 3,
    severity: 3,
    overdueDays: 17,
    trafficImpact: 52,
    safetyRisk: 46,
    resourceIds: ["r-tw14"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-ENGG-013",
    source: "TMS",
    department: "ENGG",
    title: "LWR destressing km 78–86 Up",
    detail: "Rail temperature window 32–38°C. Heat scenario will block this.",
    fromKm: 78,
    toKm: 86,
    line: "UP",
    durationHours: 4,
    severity: 3,
    overdueDays: 12,
    trafficImpact: 60,
    safetyRisk: 66,
    resourceIds: ["r-pwm-pnp"],
    earliest: E,
    latest: addDays(E, 18),
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-SNT-011",
    source: "SMMS",
    department: "SNT",
    title: "Haser unit alignment SNP home",
    detail: "Shifted after monsoon. Requires track geometry stable.",
    fromKm: 43.5,
    toKm: 44.8,
    line: "UP",
    durationHours: 2,
    severity: 3,
    overdueDays: 5,
    trafficImpact: 55,
    safetyRisk: 58,
    resourceIds: ["r-snt-pnp"],
    earliest: E,
    latest: L,
    canBundle: true,
    status: "OPEN",
  },
  {
    id: "T-ENGG-014",
    source: "TMS",
    department: "ENGG",
    title: "Completed: tamping km 50–58 Up",
    detail: "Done 02 Sep night. Left as closed-loop evidence.",
    fromKm: 50,
    toKm: 58,
    line: "UP",
    durationHours: 4,
    severity: 3,
    overdueDays: 0,
    trafficImpact: 50,
    safetyRisk: 40,
    resourceIds: ["r-unimat"],
    earliest: "2026-09-01",
    latest: "2026-09-03",
    canBundle: true,
    status: "DONE",
  },
  {
    id: "T-TRD-011",
    source: "TDMS",
    department: "TRD",
    title: "Completed: isolator SSP Karnal",
    detail: "Closed 03 Sep. Historical actual-vs-plan sample.",
    fromKm: 121,
    toKm: 125,
    line: "BOTH",
    durationHours: 3,
    severity: 3,
    overdueDays: 0,
    trafficImpact: 60,
    safetyRisk: 40,
    resourceIds: ["r-psi"],
    earliest: "2026-09-01",
    latest: "2026-09-03",
    canBundle: true,
    status: "DONE",
  },
];

export const EMERGENCY_TASK: Task = {
  id: "T-ENGG-EMG",
  source: "TMS",
  department: "ENGG",
  title: "Emergency weld failure km 91.4 Up — TSR 20",
  detail: "Rail end crack reported 04 Sep 06:10. Clamp in situ. Needs insert + USFD + bonding before TSR removal.",
  fromKm: 90.8,
  toKm: 92.0,
  line: "UP",
  durationHours: 4,
  severity: 5,
  overdueDays: 0,
  trafficImpact: 98,
  safetyRisk: 96,
  resourceIds: ["r-pwm-pnp", "r-usfd"],
  earliest: E,
  latest: addDays(E, 3),
  canBundle: true,
  status: "OPEN",
};

export const ASSETS: Asset[] = [
  { id: "a1", type: "TRACK", name: "60kg panel SNP–GNU Up", km: 46, health: 54, lastMaintained: "2026-04-12", department: "ENGG", riskNote: "Fouled ballast, TSR 30" },
  { id: "a2", type: "POINT", name: "PNP-12A turnout", km: 89.2, health: 48, lastMaintained: "2025-11-02", department: "ENGG", riskNote: "Crossing wear + hunting machine" },
  { id: "a3", type: "SIGNAL", name: "SNP Up home EI", km: 44.1, health: 41, lastMaintained: "2026-01-18", department: "SNT", riskNote: "I/O card intermittent" },
  { id: "a4", type: "OHE", name: "Contact wire PNP Up", km: 90, health: 57, lastMaintained: "2025-08-20", department: "TRD", riskNote: "25% wear, staggered" },
  { id: "a5", type: "BRIDGE", name: "Br. 214 canal girder", km: 108.5, health: 62, lastMaintained: "2025-06-01", department: "ENGG", riskNote: "Bearing inspection overdue" },
  { id: "a6", type: "LC", name: "LC-29 SMK manned", km: 63.4, health: 50, lastMaintained: "2026-02-11", department: "ENGG", riskNote: "Cess failure, boom untested" },
  { id: "a7", type: "AXLE_COUNTER", name: "KKDE Up MSDAC", km: 156.2, health: 58, lastMaintained: "2026-03-09", department: "SNT", riskNote: "False occupancy" },
  { id: "a8", type: "OHE", name: "Cantilevers GNU Up", km: 44.8, health: 46, lastMaintained: "2025-09-14", department: "TRD", riskNote: "Bent after tree fall" },
  { id: "a9", type: "TRACK", name: "LWR km 78–86 Up", km: 82, health: 68, lastMaintained: "2026-05-22", department: "ENGG", riskNote: "Destressing due" },
  { id: "a10", type: "TRACK", name: "60kg SHDM Dn GMT", km: 173, health: 52, lastMaintained: "2024-12-08", department: "ENGG", riskNote: "GMT expired" },
  { id: "a11", type: "TSS", name: "SSP Panipat", km: 89, health: 71, lastMaintained: "2026-07-01", department: "TRD", riskNote: "Isolator sluggish" },
  { id: "a12", type: "SIGNAL", name: "GRA Dn distant LED", km: 110.4, health: 64, lastMaintained: "2025-10-19", department: "SNT", riskNote: "Lamp voltage low" },
  { id: "a13", type: "OHE", name: "ATD SNP–GNU Dn", km: 50, health: 66, lastMaintained: "2025-12-02", department: "TRD", riskNote: "Winter setting overdue" },
  { id: "a14", type: "POINT", name: "KUN-3B", km: 123.2, health: 73, lastMaintained: "2026-06-14", department: "SNT", riskNote: "Detection drift" },
  { id: "a15", type: "TRACK", name: "Formation ANDI Dn", km: 13.2, health: 61, lastMaintained: "2026-08-02", department: "ENGG", riskNote: "Monsoon slacks, TSR 20" },
  { id: "a16", type: "OHE", name: "Section insulator NUR Up", km: 27, health: 69, lastMaintained: "2025-11-28", department: "TRD", riskNote: "Wear on runner" },
  { id: "a17", type: "BRIDGE", name: "RUB km 4.8 SZM", km: 4.8, health: 88, lastMaintained: "2026-07-20", department: "ENGG", riskNote: "Sound" },
  { id: "a18", type: "SIGNAL", name: "NDLS–SZM TPWS", km: 3, health: 77, lastMaintained: "2026-04-04", department: "SNT", riskNote: "Balise calibration leftover" },
  { id: "a19", type: "TRACK", name: "UMB catch siding", km: 198.4, health: 80, lastMaintained: "2026-01-30", department: "ENGG", riskNote: "Annual due" },
  { id: "a20", type: "OHE", name: "KKDE Up insulators", km: 158, health: 63, lastMaintained: "2026-02-22", department: "TRD", riskNote: "Pollution film" },
];

export const TRAINS: TrainPath[] = [
  { number: "12005", name: "Kalka Shatabdi", dir: "UP", passPnp: "08:04", class: "SHATABDI" },
  { number: "12006", name: "Kalka Shatabdi", dir: "DN", passPnp: "19:42", class: "SHATABDI" },
  { number: "12011", name: "Kalka Shatabdi", dir: "UP", passPnp: "18:22", class: "SHATABDI" },
  { number: "12012", name: "Kalka Shatabdi", dir: "DN", passPnp: "10:18", class: "SHATABDI" },
  { number: "12013", name: "Amritsar Shatabdi", dir: "UP", passPnp: "17:10", class: "SHATABDI" },
  { number: "12029", name: "Swarna Shatabdi", dir: "UP", passPnp: "08:38", class: "SHATABDI" },
  { number: "12497", name: "Shan-e-Punjab", dir: "UP", passPnp: "09:16", class: "MAIL" },
  { number: "12925", name: "Paschim Express", dir: "DN", passPnp: "11:05", class: "MAIL" },
  { number: "11077", name: "Jhelum Express", dir: "UP", passPnp: "22:48", class: "MAIL" },
  { number: "11078", name: "Jhelum Express", dir: "DN", passPnp: "04:12", class: "MAIL" },
  { number: "14033", name: "Jammu Mail", dir: "UP", passPnp: "21:55", class: "MAIL" },
  { number: "54541", name: "Meerut–UMB Passenger", dir: "UP", passPnp: "12:40", class: "PASS" },
  { number: "G-14", name: "Container rake TKD–LDH", dir: "UP", passPnp: "01:20", class: "GOODS" },
  { number: "G-09", name: "Coal rake to PTK", dir: "UP", passPnp: "02:45", class: "GOODS" },
  { number: "G-22", name: "Empty BOXN return", dir: "DN", passPnp: "03:10", class: "GOODS" },
];

function datesInclusive(start: string, end: string) {
  const out: string[] = [];
  let d = start;
  while (d <= end) {
    out.push(d);
    d = addDays(d, 1);
  }
  return out;
}

function dow(iso: string) {
  const [y, m, d] = iso.split("-").map(Number);
  return new Date(Date.UTC(y, m - 1, d)).getUTCDay();
}

export function buildWindows(sundayMega = true): WindowSlot[] {
  const days = datesInclusive(WEEK_START, HORIZON_END);
  const slots: WindowSlot[] = [];
  for (const date of days) {
    const w = dow(date);
    slots.push({
      id: `w-${date}-n`,
      date,
      startMin: 40,
      endMin: 280,
      kind: "NIGHT",
      line: "BOTH",
      fromKm: 0,
      toKm: 199,
      disruptionCost: 38,
    });
    if (w === 2 || w === 4) {
      slots.push({
        id: `w-${date}-m`,
        date,
        startMin: 670,
        endMin: 790,
        kind: "MIDDAY",
        line: "BOTH",
        fromKm: 0,
        toKm: 199,
        disruptionCost: 96,
      });
    }
    if (w === 0 && sundayMega) {
      slots.push({
        id: `w-${date}-x`,
        date,
        startMin: 480,
        endMin: 840,
        kind: "MEGA",
        line: "BOTH",
        fromKm: 0,
        toKm: 199,
        disruptionCost: 110,
      });
    }
  }
  return slots;
}

export const WINDOWS = buildWindows(true);

export function stationAt(km: number): Station {
  let best = STATIONS[0];
  for (const s of STATIONS) {
    if (Math.abs(s.km - km) < Math.abs(best.km - km)) best = s;
  }
  return best;
}

export function sectionFor(km: number): SectionRow {
  return SECTIONS.find((s) => km >= s.fromKm && km <= s.toKm) ?? SECTIONS[SECTIONS.length - 1];
}
